import React, { useState } from 'react';
import {
  View,
  Text,
  Modal,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Colors, FontSize, FontWeight, Spacing, Radius } from '../constants/theme';

// ─── Section types ────────────────────────────────────────────────────────────

interface PrivacySection {
  icon: keyof typeof Ionicons.glyphMap;
  iconColor: string;
  title: string;
  items: string[];
}

const SECTIONS: PrivacySection[] = [
  {
    icon: 'phone-portrait-outline',
    iconColor: '#6C8EBF',
    title: 'What stays on your device',
    items: [
      'Goals, rules, and focus sessions — stored locally in AsyncStorage',
      'Daily plans, reflections, and distraction logs',
      'All data works fully offline — no internet required',
      'Cloud sync is optional and only uploads to your private Supabase account',
    ],
  },
  {
    icon: 'cloud-outline',
    iconColor: Colors.gold,
    title: 'What cloud sync stores',
    items: [
      'Goals and skill plans (synced to your private database)',
      'Focus sessions and schedule events',
      'Memories and reflections (if you have an account)',
      'Only your account can read your data — row-level security enforced',
    ],
  },
  {
    icon: 'sparkles-outline',
    iconColor: '#818CF8',
    title: 'What the AI can access',
    items: [
      'Your recent memories (up to 30 most recent entries)',
      'Your active goals and their weekly targets',
      'Course readiness scores and academic risk levels',
      'Project health scores and blocked milestones',
      'Today\'s focus session and reflection',
      'The AI never receives raw passwords, payment info, or device data',
    ],
  },
  {
    icon: 'lock-closed-outline',
    iconColor: '#4ADE80',
    title: 'What the AI cannot access',
    items: [
      'Your authentication credentials or Supabase tokens',
      'Other users\' data — all queries are row-level scoped to your account',
      'Your device contacts, camera, microphone, or location',
      'Any data you have not explicitly entered into LifeOS',
    ],
  },
  {
    icon: 'library-outline',
    iconColor: '#F472B6',
    title: 'How the Memory Engine works',
    items: [
      'Memories you save are stored locally and optionally in your cloud database',
      'Each memory is converted to a vector embedding for semantic search',
      'The AI retrieves the most relevant memories when answering your questions',
      'You can delete any memory at any time — it is removed from both local storage and the cloud',
    ],
  },
  {
    icon: 'analytics-outline',
    iconColor: '#FB923C',
    title: 'How recommendations are generated',
    items: [
      'Readiness scores are computed locally from your study notes and exam dates',
      'Project health is computed from milestone status, velocity, and activity recency',
      'Goal risk is computed from weekly hours tracked vs. target',
      'Recommendations are generated by the AI using this computed context — no manual curation',
      'The AI explains its reasoning in every response so you can evaluate it yourself',
    ],
  },
  {
    icon: 'bar-chart-outline',
    iconColor: Colors.textMuted,
    title: 'Analytics & telemetry',
    items: [
      'LifeOS tracks aggregate product events (e.g., "memory created", "walkthrough completed")',
      'Events contain no personal content — only counts and boolean flags',
      'Your user ID is used for session correlation, not for ad targeting',
      'You can opt out of analytics in Settings at any time',
    ],
  },
];

// ─── PrivacyModal ─────────────────────────────────────────────────────────────

interface PrivacyModalProps {
  visible: boolean;
  onClose: () => void;
}

export function PrivacyModal({ visible, onClose }: PrivacyModalProps) {
  const [expanded, setExpanded] = useState<number | null>(null);

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <View style={s.root}>
        {/* Header */}
        <View style={s.header}>
          <View>
            <Text style={s.headerLabel}>LifeOS</Text>
            <Text style={s.headerTitle}>Privacy & Trust</Text>
          </View>
          <TouchableOpacity onPress={onClose} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
            <Ionicons name="close" size={24} color={Colors.textSecondary} />
          </TouchableOpacity>
        </View>

        <ScrollView
          contentContainerStyle={s.content}
          showsVerticalScrollIndicator={false}
        >
          {/* Intro */}
          <View style={s.intro}>
            <View style={s.introIconWrap}>
              <Ionicons name="shield-checkmark-outline" size={28} color={Colors.gold} />
            </View>
            <Text style={s.introText}>
              LifeOS is built on a simple principle: your life data belongs to you.
              No ads. No data brokering. No black-box AI decisions.
            </Text>
          </View>

          {/* Sections */}
          {SECTIONS.map((section, i) => (
            <TouchableOpacity
              key={i}
              style={s.section}
              onPress={() => setExpanded(expanded === i ? null : i)}
              activeOpacity={0.75}
            >
              <View style={s.sectionHeader}>
                <View style={[s.sectionIcon, { backgroundColor: section.iconColor + '1A' }]}>
                  <Ionicons name={section.icon} size={18} color={section.iconColor} />
                </View>
                <Text style={s.sectionTitle}>{section.title}</Text>
                <Ionicons
                  name={expanded === i ? 'chevron-up' : 'chevron-down'}
                  size={14}
                  color={Colors.textMuted}
                />
              </View>

              {expanded === i && (
                <View style={s.sectionBody}>
                  {section.items.map((item, j) => (
                    <View key={j} style={s.bullet}>
                      <View style={[s.dot, { backgroundColor: section.iconColor }]} />
                      <Text style={s.bulletText}>{item}</Text>
                    </View>
                  ))}
                </View>
              )}
            </TouchableOpacity>
          ))}

          {/* Footer */}
          <View style={s.footer}>
            <Ionicons name="heart-outline" size={14} color={Colors.textMuted} />
            <Text style={s.footerText}>
              LifeOS is designed to make you better, not to extract value from you.
              If you have questions about your data, reach out directly.
            </Text>
          </View>
        </ScrollView>
      </View>
    </Modal>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const s = StyleSheet.create({
  root:   { flex: 1, backgroundColor: Colors.background },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  headerLabel: {
    fontSize: FontSize.xs,
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: Colors.textPrimary,
  },

  content: { padding: Spacing.lg, gap: Spacing.sm, paddingBottom: Spacing.xxl },

  intro: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md,
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.gold + '33',
    padding: Spacing.md,
    marginBottom: Spacing.xs,
  },
  introIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.gold + '1A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  introText: {
    flex: 1,
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    lineHeight: 22,
  },

  section: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.md,
  },
  sectionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    flex: 1,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.textPrimary,
  },

  sectionBody: {
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.md,
    gap: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: Spacing.sm,
  },
  bullet: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    marginTop: 7,
    flexShrink: 0,
  },
  bulletText: {
    flex: 1,
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    lineHeight: 21,
  },

  footer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    paddingTop: Spacing.md,
  },
  footerText: {
    flex: 1,
    fontSize: FontSize.xs,
    color: Colors.textMuted,
    lineHeight: 18,
    fontStyle: 'italic',
  },
});
